/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rosinante.tugasdaripakfaqih;

import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author KOCHOR
 */
public class InputDataFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputDataFrame
     */
    String kategori;
    private static final String DATABASE_URL = "https://touri-dinacom.firebaseio.com/";

    private static DatabaseReference database;

    public InputDataFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radio_button_pemasukan = new javax.swing.JRadioButton();
        radio_button_pengeluaran = new javax.swing.JRadioButton();
        jenis_data_label1 = new javax.swing.JLabel();
        text_field_input_data = new javax.swing.JTextField();
        button_input_data2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jenis_data_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radio_button_pemasukan.setSelected(true);
        radio_button_pemasukan.setText("Pemasukan");
        radio_button_pemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_button_pemasukanActionPerformed(evt);
            }
        });

        radio_button_pengeluaran.setText("Pengeluaran");
        radio_button_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_button_pengeluaranActionPerformed(evt);
            }
        });

        jenis_data_label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jenis_data_label1.setText("Input Data");

        button_input_data2.setText("Input Data");
        button_input_data2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_input_data2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Pengeluaran");

        jenis_data_label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jenis_data_label.setText("Jenis Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis_data_label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_button_pemasukan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_button_pengeluaran)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jenis_data_label1)
                                    .addComponent(text_field_input_data, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_input_data2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jenis_data_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_button_pemasukan)
                    .addComponent(radio_button_pengeluaran))
                .addGap(18, 18, 18)
                .addComponent(jenis_data_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_field_input_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(button_input_data2)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_button_pemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_button_pemasukanActionPerformed
        kategori = "pemasukan";
    }//GEN-LAST:event_radio_button_pemasukanActionPerformed

    private void radio_button_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_button_pengeluaranActionPerformed
        kategori = "pengeluaran";
    }//GEN-LAST:event_radio_button_pengeluaranActionPerformed

    private void button_input_data2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_input_data2ActionPerformed

        int jumlah = Integer.parseInt(text_field_input_data.getText());
        if (kategori.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kategori Belum Dipilih!");
        } else if (String.valueOf(jumlah).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Jumlah Belum Diisi!");
        } else {
            database = FirebaseDatabase.getInstance().getReference("data_tugas" + "/" + kategori);
            String uploadId = database.push().getKey();
            TabelModel tabelModel = new TabelModel(String.valueOf(jumlah), kategori);
            database.child(uploadId).setValue(tabelModel);
            JOptionPane.showMessageDialog(this, tabelModel.getDataPengeluaran() + " " + tabelModel.getKategori());
//            TabelPengeluaranFrame tabelDataPengeluaranFrame = new TabelPengeluaranFrame();
//            tabelDataPengeluaranFrame.show();
        }
    }//GEN-LAST:event_button_input_data2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InputDataFrame().setVisible(true);
        });
        // Initialize Firebase
        try {
            // [START initialize]
            FileInputStream serviceAccount = new FileInputStream("touri-dinacom-firebase-adminsdk-aozcy-920c20d745.json");
            FirebaseOptions options = new FirebaseOptions.Builder()
                    .setCredentials(GoogleCredentials.fromStream(serviceAccount))
                    .setDatabaseUrl(DATABASE_URL)
                    .build();
            FirebaseApp.initializeApp(options);
            // [END initialize]
        } catch (IOException e) {
            System.out.println("ERROR: invalid service account credentials. See README.");
            System.out.println(e.getMessage());

            System.exit(1);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_input_data;
    private javax.swing.JButton button_input_data1;
    private javax.swing.JButton button_input_data2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jenis_data_label;
    private javax.swing.JLabel jenis_data_label1;
    private javax.swing.JRadioButton radio_button_pemasukan;
    private javax.swing.JRadioButton radio_button_pengeluaran;
    private javax.swing.JTextField text_field_input_data;
    // End of variables declaration//GEN-END:variables
}
